.travis.yml
package.json

This PR updates the Node versions that we test against on CI and officially declares the supported versions in the `package.json` file. Supported after this PR are Node 6, 8 and 10, which are the currently officially supported Node versions.
Since we previously tested against Node 0.10 and 0.11 this should be considered a breaking change, and the next release should bump the minor version since we're still pre-1.0.

Update Node version requirements

---

.eslintrc.js
examples/basic-usage-examples.js
examples/col-and-row-span-examples.js
lib/print-example.js
package.json
src/cell.js
src/layout-manager.js
src/table.js
src/utils.js
test/cell-test.js
test/example-tests.js
test/layout-manager-test.js
test/original-cli-table-index-tests.js
test/original-cli-table-newlines-test.js
test/table-layout-test.js
test/table-test.js
test/utils-test.js
test/verify-legacy-compatibility-test.js
yarn.lock

see https://eslint.org/ and https://prettier.io/

Add ESLint and Prettier

---

README.md
gulpfile.js
lib/print-example.js
package.json
scripts/print-examples.js
scripts/update-docs.js
yarn.lock

This PR replaces the remaining gulp tasks with two basic Node.js scripts and finally removes the gulp dependency.

Remove Gulp

---

package.json
src/cell.js
src/layout-manager.js
test/table-layout-test.js

Replace `kind-of` dependency with `typeof` and `Array.isArray()`

---

index.d.ts

Suggested fix for the "Table" union type definition error

"Table" union type definition fix

---

README.md

This fixes the mixed content on npmjs.com and we should alsways link to the https version.

docs: use https

---

.travis.yml
package.json

These versions are no longer maintained by the Node.js team, so we should drop support to unblock some of the open dependency updates.
Closes #133

Drop support for Node 6 and 8

---

README.md

The credits to Guillermo are incorrect, and the links to the correct GitHub have been updated.

Updated Readme: Incorrect Credit Attribution

---

package.json
src/layout-manager.js
src/utils.js
yarn.lock

cli-table3 can use Object.assign() directly since it targets Node.js 10+.

Remove obsolete `Object.assign()` polyfill

---

package.json

Mainly, this https://github.com/Marak/colors.js/issues/285 Latest version has been compromised. A  former maintainer, @dabh, has released this alternative 1.4.0 version.
Alternatively, it could simply be eliminated, since it's optional.

`colors.js` has issues

---

.github/workflows/test.yml
README.md

To address #271, this incorporates a github action which should run the tests across the same [major] versions of node as was previously setup with Travis.
[Attempting this PR from a non-fork branch to attempt to induce the action]

Initial workflow action for testing PRs and commits to master

---

package.json
yarn.lock

When installing devDependencies, eslint is missing as a peer dependency:
```
...
➭ yarn install --frozen-lockfile
yarn install v1.22.15
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > eslint-config-prettier@6.15.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-plugin-prettier@3.4.0" has unmet peer dependency "eslint@>=5.0.0".
warning " > jest-runner-eslint@0.7.6" has unmet peer dependency "eslint@^4.0.0 || ^5.0.0 || ^6.0.0".
[5/5] 🔨  Building fresh packages...
✨  Done in 3.63s.
```
This PR adds the missing dependency (eslint@^6.0.0).
```
➭ rm -fr node_modules && yarn install --frozen-lockfile
yarn install v1.22.15
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving …
```

Fix missing eslint peer dependency (affects dev only)

---

test/verify-legacy-compatibility-test.js

This mocks the colors module within the "legacy tests" to produce consistent output from colors—as the tests expect.
This one-liner appropriately resolves #196.

#196 - Fix to failing unit tests

---

README.md
basic-usage.md
examples/basic-usage-examples.js
index.d.ts
src/cell.js
src/utils.js
test/utils-test.js

This is in response to #125:
The current wordWrap functionality wraps only on space characters and truncates overhanging text.
```
const table = new Table({
head: ['1234', '1234'],
colWidths: [4, 4],
wordWrap: true,
});
table.push(['one', 'The Quick']);
table.push(['two', 'Brown Fox']);
table.push(['three', 'Jumped Over']);
table.push(['four', 'A Lazy']);
table.push(['five', 'Dog']);
console.log(table.toString());
```
```
┌────┬────┐
│ 1… │ 1… │
├────┼────┤
│ o… │ T… │
│    │ Q… │
├────┼────┤
│ t… │ B… │
│    │ F… │
├────┼────┤
│ t… │ J… │
│    │ O… │
├────┼────┤
│ f… │ A  │
│    │ L… │
├────┼────┤
│ f… │ D… │
└────┴────┘
```
---
The "wrapWords" option produces an alternative word wrapping that truly wraps without truncating words.
```
const table = new Table({
head: ['1234', '1234'], …
```

[Feature] - Alternative word wrap option

---

package.json
src/layout-manager.js
test/issues/269-test.js
test/table-test.js

Been attempting to ensure support for all varieties of table-layouts as well as reducing the time-complexity. This PR will solve #269 as well as open the door to supporting larger datasets and faster rendering.
Previously, when layout is being calculated, for each cell in the table it would traverse all cells that had come before it. It was not able to detect rowSpans left-wards beyond the immediate left. Not sure how to express this mathematically, but the time-complexity is/was exponential.
With this refactored table layout, the time-complexity is mostly reduced to match the complexity of the table. 
**The first commit includes failing tests.** One specifically for #269 and one generally that demonstrates an advanced implementation of rowSpan and colSpan.

#269 - Refactored table layouts

---

src/cell.js
test/issues/124-test.js

This addresses the issue reported in #124.
When setting cell options, it was taking the first truthy value and therefore any zero (0) values were being ignored.

Fix: Correctly set cell padding for zero values

---

README.md
src/cell.js
src/debug.js
src/layout-manager.js
src/table.js
test/table-test.js

This is a first stab at #279. Hoping to clean it up and add some more tests. But striving to get this in before further refactoring.

Add debugging capabilities

---

src/layout-manager.js
test/issues/289-test.js

This PR includes failing tests in the first commit with a fix for the issue described in #289 in the second.

Fix to erroneous column truncation when using colSpan (#289)

---

basic-usage.md
examples/basic-usage-examples.js
lib/print-example.js
src/cell.js
src/utils.js
test/utils-test.js

This PR adds support for hyperlinks using a very simple interface. This feature was requested in #73 
```
table.push([
// Specify the URL as the display text
{ href: 'http://example.com' }, 
// Specify display text
{ href: 'http://example.com', content: 'Example text' },
]);
```
**Link text is wrapped, truncated, etc. as usual but when the text of a cell spans multiple lines, each link is wrapped with the link.**
PR includes:
- Added `utils.hyplerink()` with unit tests (with credits to @matheussampaio)
- Added hyperlink support to `Cell` with functional tests that generate documentation
- Updated documentation `basic-usage.md`
The difference in functionality is not meaningfully demonstrable in markdown. Examine the (failing/passing) tests in _Checks_ to inspect the differences.

Hyperlink support for cells

---

src/cell.js
test/cell-test.js

This adds the ability to set `wordWrap` and `wrapOnWordBoundary` options per cell, instead of it being set globally via the table options.
Use case is for when you want one column to have `wrapOnWordBoundary=false`, and another column with `wrapOnWordBoundary=true` (see screenshot and sample code)
```javascript
const Table = require("cli-table3");
let table = new Table({
style: { head: [], border: [] },
colWidths: [15, 50],
wordWrap: true,
wrapOnWordBoundary: true
});
table.push(
['URLs', 'Description'],
[{ content: 'https://en.wikipedia.org/wiki/Voyager_program', wrapOnWordBoundary: false }, { content: 'The Voyager program is an American scientific program that employs two robotic interstellar probes, Voyager 1 and Voyager 2. They were launched in 1977 to take advantage of a favorable …
```

feat: ability to set/override wordWrap and wrapOnWordBoundary options per cell

---

index.d.ts

The code supports setting `wordWrap` and `wrapOnWordBoundary` on a per-cell basis, but the Typescript definitions do not.

add word wrap options to CellOptions ts interface

---

.eslintrc.js
index.d.ts
src/cell.js
test/cell-test.js

The existing type casting (`String(value)`) also works for `BigInt`s, so I've added support in the Typescript definitions and the JS type checks.

support bigint cell content type

---

src/utils.js
test/issues/338-test.js

closes #338  
This is a bad solution, and I understand if you'd prefer not to merge it.

Fix truncated href tags
